# see https://github.com/srvaroa/labeler
version: 1
issues: False
labels:
- label: "bug"
  title: "^fix(\\(.*\\))?:.*"
- label: "dependencies"
  title: "^deps(\\(.*\\))?:.*"
- label: "documentation"
  title: "^docs(\\(.*\\))?:.*"
- label: "enhancement"
  title: "^(enh|feat)(\\(.*\\))?:.*"
- label: "work-in-progress"
  title: "^WIP:.*"
  mergeable: false
